version: '2'
services:
    gateway-app:
        image: gateway
        external_links:
            - gateway-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/gateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=80
        ports:
            - 8080:8080
    gateway-postgresql:
        container_name: gateway-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=
    
    goblob-app:
        image: goblob
        external_links:
            - goblob-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/goblob
            - JHIPSTER_SLEEP=10
    goblob-postgresql:
        container_name: goblob-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=goblob
            - POSTGRES_PASSWORD=
    
    uaa-app:
        image: uaa
        external_links:
            - uaa-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/uaa
            - JHIPSTER_SLEEP=10
    uaa-postgresql:
        container_name: uaa-postgresql
        image: postgres:9.5.4
        environment:
            - POSTGRES_USER=uaa
            - POSTGRES_PASSWORD=
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry


